package com.example.englishLearnForKids.other


import com.example.englishlearnforkids.R


class AlphabetMembers {
    val list= listOf(
        AlphabetItem(
            "A",
            "a",
            R.drawable.apple,
            "apple",
            R.raw.a
        ),
        AlphabetItem(
            "B",
            "b",
            R.drawable.ball,
            "ball",
            R.raw.b
                ),
        AlphabetItem(
            "C",
            "c",
            R.drawable.cat,
            "cat",
            R.raw.c
                ),
        AlphabetItem(
            "D",
            "d",
            R.drawable.dog,
            "dog",
            R.raw.d
                ),
        AlphabetItem(
            "E",
            "e",
             R.drawable.elephant,
            "elephant",
            R.raw.e
                ),
        AlphabetItem(
            "F",
            "f",
            R.drawable.fish,
            "fish",
            R.raw.f
                ),
        AlphabetItem(
            "G",
            "g",
            R.drawable.giraffe,
            "giraffe",
            R.raw.g
                ),
        AlphabetItem(
            "H",
            "h",
            R.drawable.hat,
            "hat",
            R.raw.h
                ),
        AlphabetItem(
            "I",
            "i",
            R.drawable.ice_cream,
            "ice cream",
            R.raw.i
                ),
        AlphabetItem(
            "J",
            "j",
            R.drawable.juice,
            "juice",
            R.raw.j
                ),
        AlphabetItem(
            "K",
            "k",
            R.drawable.kite,
            "kite",
            R.raw.k
                ),
        AlphabetItem(
            "L",
            "l",
            R.drawable.lion,
            "lion",
            R.raw.l
                ),
        AlphabetItem(
            "M",
            "m",
            R.drawable.monkey,
            "monkey",
            R.raw.m
                ),
        AlphabetItem(
            "N",
            "n",
            R.drawable.nest,
            "nest",
            R.raw.n
                ),
        AlphabetItem(
            "O",
            "o",
            R.drawable.orange,
            "orange",
            R.raw.o
                ),
        AlphabetItem(
            "P",
            "p",
            R.drawable.penguin,
            "penguin",
            R.raw.p
                ),
        AlphabetItem(
            "Q",
            "q",
            R.drawable.queen,
            "queen",
            R.raw.q
                ),
        AlphabetItem(
            "R",
            "r",
            R.drawable.rainbow,
            "rainbow",
            R.raw.r
                ),
        AlphabetItem(
            "S",
            "s",
            R.drawable.sun,
            "sun",
            R.raw.s
                ),
        AlphabetItem(
            "T",
            "t",
            R.drawable.tiger,
            "tiger",
            R.raw.t
                ),
        AlphabetItem(
            "U",
            "u",
            R.drawable.umbrella,
            "umbrella",
            R.raw.u
                ),
        AlphabetItem(
            "V",
            "v",
            R.drawable.violin,
            "violin",
            R.raw.v
                ),
        AlphabetItem(
            "W",
            "w",
            R.drawable.whale,
            "whale",
            R.raw.w
                ),
        AlphabetItem(
            "X",
            "x",
            R.drawable.xylophone,
            "xylophone",
            R.raw.x
                ),
        AlphabetItem(
            "Y",
            "y",
            R.drawable.yoyo,
            "yo-yo",
            R.raw.y
                ),
        AlphabetItem(
            "Z",
            "z",
            R.drawable.zebra,
            "zebra",
            R.raw.z
        )

    )
}